server:
  port: 9050

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/ips?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: ichiken
    password: 102938

  data:
    redis:
      host: 192.168.0.10
      port: 6379
      password: 102938

mqtt:
  url: tcp://192.168.0.10:1883
  client-id: ${random.uuid}
  username: ichiken
  password: ichiken2023
  subscribe-topics:
    - /ips/pub/AOA_data
    - /ips/pub/station_online_status
    - /ips/pub/AOA_Station_His

external:
  url: http://192.168.0.10:8888/

springdoc:
  swagger-ui:
    tags-sorter: alpha
  writer-with-order-by-keys: true

knife4j:
  enable: true
  setting:
    enable-dynamic-parameter: true
    enable-swagger-models: false
    enable-footer: false

mybatis-plus:
  type-handlers-package: com.lgguan.iot.position.mapper.handler
  global-config:
    db-config:
      update-strategy: ignored

indoor:
  file:
    path: /Users/aaron/Desktop/dockerxx/files
    #path: C:\indoor
    prefix: /download
    domain: 192.168.0.17:9050